name: Deploy Storybook to S3

on:
  push:
    branches:
      - main # メインブランチにpushされた時

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@main
        # - uses: jakejarvis/s3-sync-action@master
        # with:
        #   args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
    - name: Deploy
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 cp --recursive --region ap-northeast-1 / s3://s3deploy-oligeon
